version: '3.2'
services:
  web:
    restart: always
    network_mode: "host"
    build: .
    command: bundle exec rails server -p ${APP_PORT} 
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    volumes:
      - .:/myapp

  db:
    restart: always
    command: -p ${DB_PORT}
    network_mode: "host"
    image: postgres:alpine
    volumes:
      #- ./postgresql.conf:/usr/local/share/postgresql/postgresql.conf
      - /data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER} # read from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  sidekiq:
    restart: always
    network_mode: "host"
    env_file:
      - .env
    build: .
    volumes:
      - .:/myapp
    command: bundle exec sidekiq
  redis:
    restart: always
    network_mode: "host"
    image: redis:alpine
    command: redis-server
