version: '3.2'
services:
  web:
    build: .
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true # TODO-remove: configure nginx and remove this line
    volumes:
      - .:/myapp
    ports:
      - ${APP_PORT}:3000
  db:
    image: postgres:alpine
#    ports:
#      - ${DB_PORT}:5432
    volumes:
      #- ./postgresql.conf:/usr/local/share/postgresql/postgresql.conf
      - /data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER} # read from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  sidekiq:
    build: .
    volumes:
      - .:/myapp
    command: bundle exec sidekiq
  redis:
    image: redis:alpine
    command: redis-server
#    ports:
#      - ${REDIS_PORT}:6379
