version: '3.2'
services:
  web:
    container_name: genius
    build: .
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true # TODO-remove: configure nginx and remove this line
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      #- /home/ubuntu/an_x/genius-center13000/postgresql.conf:/usr/local/share/postgresql/postgresql.conf
      - /data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  sidekiq:
    build: .
    volumes:
      - .:/myapp
    command: bundle exec sidekiq
    environment:
      - SIDEKIQ_REDIS_URL=redis://redis:6379/10
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
